// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0gzM7HDkZd6w-iI0CnvVqg5VlMupR7-A',
    appId: '1:971040513049:android:b64f56f4bef228615f5e88',
    messagingSenderId: '971040513049',
    projectId: 'keep-notes-1ea9a',
    storageBucket: 'keep-notes-1ea9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4GfnwXEzd_e_qeaCOegxVANa7YALHfG4',
    appId: '1:971040513049:ios:93dc9426d93d31605f5e88',
    messagingSenderId: '971040513049',
    projectId: 'keep-notes-1ea9a',
    storageBucket: 'keep-notes-1ea9a.appspot.com',
    androidClientId: '971040513049-ijrm8a0tnd1e1or6mag133j0rt9ruvt2.apps.googleusercontent.com',
    iosClientId: '971040513049-mjfbnmdnb80nqv4cqkpb3itma8m7a3hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.keepNotes',
  );
}
